### ISSUE TITLE
Admin website flashes during navigation

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/Fritz.StaticWeb#15]
Looks like a dark-mode / light-mode flip when navigating

**Comment by jbw716** [comment]
Looks like this **_is_** actually caused by the Dark Reader browser extension, even with the extension set to "off". 
The "fix" for this can be observed by disabling or uninstalling the Dark Reader extension, or running the site in a private browsing tab (where browser extensions are disabled).

Apparently, Dark Reader alters default fallback styles in the browser to prevent "white flashes" when navigating between pages, because dark flashes in light mode is a lot less off-putting than light flashes in dark mode.

https://github.com/darkreader/darkreader/issues/4069

**Comment by csharpfritz** [comment]
It feels like the recommendation then is to close this issue.

Closing it for now.  If something comes up again, we can re-open

**Comment by csharpfritz** [comment]
Thank you for the research @jbw716 !

**Comment by jbw716** [comment]
I agree. Not much to be done here. Definitely Dark Reader's problem.
